services:
  client_service:
    container_name: client_service
    image: client_service
    build:
      context: ../
      dockerfile: ./Dockerfiles/service/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    environment:
      DB_HOST: client_postgres
    depends_on:
      client_postgres:
        condition: service_healthy
  client_postgres:
    container_name: client_postgres
    image: postgres
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
